#!/bin/sh
# /etc/hotplug.d/iface/99-prevent-leak


# https://nordvpn.com/tutorials/openwrt/openvpn/

if [ "$ACTION" = ifup ] && (ip a s tun0 up); then
	touch /etc/openvpn/_openvpn.lock

	if ( iptables -C forwarding_rule -j REJECT ); then
		iptables -D forwarding_rule -j REJECT
	fi
fi

if [ -e /etc/openvpn/_openvpn.lock ] && [ "$ACTION" = ifdown ] && (! ip a s tun0 up) && (! iptables -C forwarding_rule -j REJECT); then
        iptables -I forwarding_rule -j REJECT
fi
