#!/bin/sh /etc/rc.common
#


# External server to check by ping:
IPPING='8.8.8.8'

START=99
STOP=99

FINDIFNAME() {
        local N
        for N in $(uci show network | sed -nr 's:network\.(@?[a-zA-Z@0-9_]+\[?\d*\]?)\..*:\1:p'|sort -u); do
                if [ "$(uci get network.${N}.proto 2>/dev/null)" == "ncm" ]; then
                        IFNAME=${N}
                        DEVICE=$(uci get network.${IFNAME}.device 2>/dev/null)
                        DEVICE=/dev/ttyUSB0
                        APN=$(uci get network.${IFNAME}.apn 2>/dev/null)
                        APNUSER=$(uci get network.${IFNAME}.username 2>/dev/null)
                        APNPASS=$(uci get network.${IFNAME}.password 2>/dev/null)
                        IFMODE=$(uci get network.${IFNAME}.mode 2>/dev/null)
                        if [ -z ${APNPASS} ] || [ -z ${APNUSER} ] || [ -z ${APN} ] || [ -z ${DEVICE} ]; then
                                logger -t "ncm-fix[$$]" -p err "Aborted. Interface ${IFNAME} has some empty setting (device, apn, apn username, apn password or mode)"
                                exit 1
                        fi
                        [ -z $IFMODE ] \
                                && IFMODE=oem
                        break
                fi
        done

        if [ -z ${IFNAME} ]; then
                logger -t "ncm-fix[$$]" -p err "Aborted. An interface using ncm protocol wasn't found in /etc/config/network."
                exit 1
        fi

        if [ ! -e ${DEVICE} ]; then
                logger -t "ncm-fix[$$]" -p err "Aborted. No such device ${DEVICE}"
                exit 1
        fi
}

PPING() {
        local PP=0
        let PP=$(ping -c 10 ${IPPING} 2>/dev/null | sed -nr 's/.*transmitted, +([0-9]+).*/\1/p')+0
        echo $PP
}


SENDATC() {
        local N
        local DEVICE=$1
        shift
        local COMMAND=$@
        if [ -z "$DEVICE" -o -z "$COMMAND" ]; then
                logger -t "ncm-fix[$$]" -p err "Wrong arguments for the function SENDAT"
                return 1
        fi
        if [ ! -e ${DEVICE} ]; then
                logger -t "ncm-fix[$$]" -p err "Aborted. No such device ${DEVICE}"
                exit 1
        fi
        logger -t "ncm-fix[$$]" -p info "Sending ${COMMAND} to ${DEVICE}"
        timeout 2s echo -ne "${COMMAND}\r\n" > ${DEVICE}
}

BOOTNCM() {     # Arg: run - Restart device and interface
                # Arg: stop - Stop device and interface

        # Finding the first interface that use ncm as protocol in /etc/config/network
        FINDIFNAME
        logger -t "ncm-fix[$$]" -p info "Turning interface ${IFNAME} down. Starting to sending  AT commands to ${DEVICE}"
        [ "$(ifstatus ${IFNAME} 2>/dev/null | sed  -nr 's/.*\"up\": (true),/\1/p')" == "true" ] \
                && [ -n "$(ifdown ${IFNAME} 2>/dev/null)" ] \
                && logger -t "ncm-fix[$$]" -p warning "Turning interface ${INTERFACE} down failed"

        SENDATC ${DEVICE} "ATZ"
        SENDATC ${DEVICE} "AT^NDISDUP=1,0"

#       if [ "$1" == "run" ]; then
                sleep 2
                SENDATC ${DEVICE} "AT^NDISDUP=1,1,\"${APN}\",\"${APNUSER}\",\"${APNPASS}\""
                local ATMODE
                case $IFMODE in
                        lte )
                                ATMODE="03"
                        ;;
                        umts )
                                ATMODE="02"
                        ;;
                        gsm )
                                ATMODE="01"
                        ;;
                        preferlte )
                                ATMODE="030201"
                        ;;
                        preferumts )
                                ATMODE="0201"
                        ;;
                        auto )
                                ATMODE="00"
                        ;;
                esac
                [ "${IFMODE}" != "oem" ] \
                        && SENDATC ${DEVICE} "AT^SYSCFGEX=\"${ATMODE}\",3fffffff,2,4,7fffffffffffffff,,"
                logger -t "ncm-fix[$$]" -p info "AT commands ended. Turning interface ${IFNAME} up"
                [ -n "$(ifup ${IFNAME} 2>/dev/null)" ] \
                        && logger -t "ncm-fix[$$]" -p warning "Turning interface ${INTERFACE} up failed"
#       fi

}

CRONTAB() {
        if [ -e /etc/rc.d/S99ncm-fix ]; then
                if [ -z "$(sed -n "/\/etc\/init.d\/ncm-fix/p" /etc/crontabs/root 2>/dev/null)" ]; then
                        logger -t "ncm-fix[$$]" -p notice "Creating crontab rule and reloading the service"
                        echo "*/20      *       *       *       *       /etc/init.d/ncm-fix start" >> /etc/crontabs/root
                        /etc/init.d/cron reload
                fi
        else
                logger -t "ncm-fix[$$]" -p notice "Removing crontab rule and reloading the service"
                echo "$(sed "/\/etc\/init.d\/ncm-fix/d" /etc/crontabs/root 2>/dev/null)" >| /etc/crontabs/root
                /etc/init.d/cron reload
        fi
}


start() {

        local P=$(PPING)

        logger -t "ncm-fix[$$]" -p debug "Ping had ${P}0% of success"

        if [ $P -eq 0 ]; then
                logger -t "ncm-fix[$$]" -p warning "${IPPING} couldn't be pinged. Restarting ncm device"
                BOOTNCM run
                local N=0
                while [ ${N} -lt 10 ]; do
                        sleep 3
                        P=$(PPING)
                        [ ${P} -lt 2 ] \
                                && let N+=1 \
                                || break
                done
                logger -t "ncm-fix[$$]" -p notice "New ping had ${P}0% of success"
        fi
        CRONTAB

}


stop() {
        BOOTNCM stop
}

boot() {
        sleep 20
        start
}
